version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "800:8000"  # map 800 of host to 8000 of container
    volumes:
      - ./app:/app # map local .app to contain app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

      